language: python
python:   # 指定运行环境，这里会分别在 2.7 和 3.5 运行
  - '2.7'
install:
  - pip install -r requirements.txt
script:
  - PYTHONPATH=. py.test -v --cov=assertpy --cov-report term-missing tests
deploy:
  provider: pypi
  user: jayvee-yjw     # pypi 用户名
  password: XXX  # pypi 密码
  on:
    python: 2.7
    tags: true
    branch: master