language: python
python:   
  - '2.7'
before_install:
  - pip install pytest-cov
install:
  - pip install assertpy
script:
  - PYTHONPATH=. py.test -v --cov=nbtest --cov-report term-missing tests
deploy:
  provider: pypi
  user: jayvee-yjw
  password: XXX
  on:
    python: 2.7
    tags: false
    branch: master